<table>
    <thead>
        <tr>
            <th>unidad_negocio</th>
            <th>meta_unidad</th>
            <th>porcentaje_unidad</th>
            <th>meta_director</th>
            <th>porcentaje_director</th>
            <th>meta_comerciales</th>
            <th>porcentaje_comerciales</th>
            <th>Q1_%</th>
            <th>Q2_%</th>
            <th>Q3_%</th>
            <th>Q4_%</th>
            <th>Q1_$</th>
            <th>Q2_$</th>
            <th>Q3_$</th>
            <th>Q4_$</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    </tbody>
</table>
